### ISSUE TITLE
Use one coursier cache per build state

### ISSUE THREAD

**Issue by ihostage** [playframework/playframework#12007]
Right now we use a 26 cache entries (13 pair of `coursier-` and `sbt-ivy2-`) per build. It's about 20Gb that a huge and exceed a GH limit (10Gb) 😞 . And I described only PR build when we use only Java 11 and don't use Java 17. If we add Java 17 the needed cache size grater in two times 😱 

The root cause is using job name and matrix information in [coursier/cache-action](https://github.com/coursier/cache-action). 

FYI

```YAML
Binary Compatibility / JDK 11:
    - "coursier-cmd-f1008058cdfd5466013af0b19aaad5ad6efcadba"
    - "sbt-ivy2-cache-cmd-0ca2535479d6e84cb1e8caf6b9b92ca05db53e56"

Prefetch dependencies and JVMs for caching / { java-11 }:
Code Style / { java-11 }:
Code Style Docs / { java-11 }:
Publish Local / { java-11 }:
    - "coursier-cmd-matrix-0a8de89fca923c387d3e7e966f8b2cf4bc90edc5-f1008058cdfd5466013af0b19aaad5ad6efcadba"
    - "sbt-ivy2-cache-cmd-matrix-0a8de89fca923c387d3e7e966f8b2cf4bc90edc5-0ca2535479d6e84cb1e8caf6b9b92ca05db53e56"

Tests / { java-11, scala-2.13.x, sbt_test_task-test }:
    - "coursier-cmd-matrix-73a75110ee55426d331c74cb83da5e759b4755c2-f1008058cdfd5466013af0b19aaad5ad6efcadba"
    - "sbt-ivy2-cache-cmd-matrix-73a75110ee55426d331c74cb83da5e759b4755c2-0ca2535479d6e84cb1e8caf6b9b92ca05db53e56"

Tests / { java-11, scala-3.x, sbt_test_task-test }: 
    - "coursier-cmd-matrix-2c9b06e9495c8e5e00e3c849e74ebf408b45ba73-f1008058cdfd5466013af0b19aaad5ad6efcadba"
    - "sbt-ivy2-cache-cmd-matrix-2c9b06e9495c8e5e00e3c849e74ebf408b45ba73-0ca2535479d6e84cb1e8caf6b9b92ca05db53e56"
    - Restored From:
        - "coursier-cmd-matrix-28f930898e00e72aac18fb60afb2a639b18d68e5-f1008058cdfd5466013af0b19aaad5ad6efcadba"
        - "sbt-ivy2-cache-cmd-matrix-28f930898e00e72aac18fb60afb2a639b18d68e5-0ca2535479d6e84cb1e8caf6b9b92ca05db53e56"

Docs Tests / { java-11, scala-2.13.x }:
    - "coursier-cmd-matrix-0d7d17aa523d30e301516a6a7fbd3cfbbb1be555-f1008058cdfd5466013af0b19aaad5ad6efcadba"
    - "sbt-ivy2-cache-cmd-matrix-0d7d17aa523d30e301516a6a7fbd3cfbbb1be555-0ca2535479d6e84cb1e8caf6b9b92ca05db53e56"

Docs Tests / { java-11, scala-3.x }:
    - "coursier-cmd-matrix-223899257a6f5b13e388d96d5cb022dc29d2c7dd-f1008058cdfd5466013af0b19aaad5ad6efcadba"
    - "sbt-ivy2-cache-cmd-matrix-223899257a6f5b13e388d96d5cb022dc29d2c7dd-0ca2535479d6e84cb1e8caf6b9b92ca05db53e56"

Scripted Tests / { java-11, scala-2.13.x, sbt-1.9.6, sbt_steps-*1of3 }:
    - "coursier-cmd-matrix-865e8ff715886f6b71b269bbf79679362610ceb5-f1008058cdfd5466013af0b19aaad5ad6efcadba"
    - "sbt-ivy2-cache-cmd-matrix-865e8ff715886f6b71b269bbf79679362610ceb5-0ca2535479d6e84cb1e8caf6b9b92ca05db53e56"

Scripted Tests / { java-11, scala-2.13.x, sbt-1.9.6, sbt_steps-*2of3 }:
    - "coursier-cmd-matrix-b6441f740b339cbc2b616d61868f7380e19acd05-f1008058cdfd5466013af0b19aaad5ad6efcadba"
    - "sbt-ivy2-cache-cmd-matrix-b6441f740b339cbc2b616d61868f7380e19acd05-0ca2535479d6e84cb1e8caf6b9b92ca05db53e56"

Scripted Tests / { java-11, scala-2.13.x, sbt-1.9.6, sbt_steps-*3of3 }:
    - "coursier-cmd-matrix-60398f3d9be83c4bc7ce1b8ffbaf621cc581afbd-f1008058cdfd5466013af0b19aaad5ad6efcadba"
    - "sbt-ivy2-cache-cmd-matrix-60398f3d9be83c4bc7ce1b8ffbaf621cc581afbd-0ca2535479d6e84cb1e8caf6b9b92ca05db53e56"

Scripted Tests / { java-11, scala-3.x, sbt-1.9.6, sbt_steps-*1of3 }:
    - "coursier-cmd-matrix-569b37eb42fef1cc6f7ddfbdf9e08542c8779fcd-f1008058cdfd5466013af0b19aaad5ad6efcadba"
    - "sbt-ivy2-cache-cmd-matrix-569b37eb42fef1cc6f7ddfbdf9e08542c8779fcd-0ca2535479d6e84cb1e8caf6b9b92ca05db53e56"

Scripted Tests / { java-11, scala-3.x, sbt-1.9.6, sbt_steps-*2of3 }:
    - "coursier-cmd-matrix-757e0b21c1c656f68962e92bea5051c8c753ce93-f1008058cdfd5466013af0b19aaad5ad6efcadba"
    - "sbt-ivy2-cache-cmd-matrix-757e0b21c1c656f68962e92bea5051c8c753ce93-0ca2535479d6e84cb1e8caf6b9b92ca05db53e56"

Publish Local / { java-11 } / Custom:
    - "play-published-local-46b7e3cd07d4af96028363d1fb4855a0a4a932f3-true"

Scripted Tests / { java-11, scala-3.x, sbt-1.9.6, sbt_steps-*3of3 }:
    - "coursier-cmd-matrix-25bbbbfddae1a89e3b6251b6b11bdf9c337834da-f1008058cdfd5466013af0b19aaad5ad6efcadba"
    - "sbt-ivy2-cache-cmd-matrix-25bbbbfddae1a89e3b6251b6b11bdf9c337834da-0ca2535479d6e84cb1e8caf6b9b92ca05db53e56"
```
